### ISSUE TITLE
经验分享：务必将router思维转向window.location.href

### ISSUE THREAD

**Issue by Baiyuetribe** [Baiyuetribe/nuxt3-naive-ui-starter#10]
由于Nuxt3说明文档极简，渲染SEO应用实际上是固定输出到浏览器客户端，因此本地的路由`router`全都不能使用，必须要转向`window.location.href`。该问题被我折腾了好几天才想清楚，啊啊啊，尝鲜代价有多痛

**Comment by itshizhan** [comment]
我觉得应该是nuxt3的bug，或用法不对
NuxtLink 不是每次都走服务端的

**Comment by Baiyuetribe** [comment]
这里我特指router，NuxtLink在temple模板里肯定正常，但是函数里不能用router思维，正确做法是调用`navigateTo`这个函数，等效于NuxtLink，可惜官网没介绍。
