### ISSUE TITLE
vite 的 build 配置里没有 transpile 字段, 在你的配置中这里是怎么加进去的

### ISSUE THREAD

**Issue by ka3hun9** [Baiyuetribe/nuxt3-naive-ui-starter#12]
![image](https://user-images.githubusercontent.com/22870150/157385419-dc676ef8-9a2e-4497-add5-355b3b79c878.png)

![image](https://user-images.githubusercontent.com/22870150/157385704-f5d270d3-b17e-4bb4-bea4-361b70d9fcb8.png)

**Comment by noahlann** [comment]
这个似乎是nuxt的配置吧。

**Comment by Baiyuetribe** [comment]
`transpile`是nuxt里的配置，我项目也没有这个呀
