### ISSUE TITLE
当前版本运行 `npm run dev` 后报错

### ISSUE THREAD

**Issue by dallaslu** [Baiyuetribe/nuxt3-naive-ui-starter#15]
(node:93509) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
    (Use `node --trace-warnings ...` to show where the warning was created)
    
     ERROR  [worker] Worker terminated due to reaching memory limit: JS heap out of memory
    
      at new NodeError (node:internal/errors:371:5)
      at Worker.[kOnExit] (node:internal/worker:276:26)
      at Worker.<computed>.onexit (node:internal/worker:198:20)

**Comment by Baiyuetribe** [comment]
> ```
> (node:93509) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
> (Use `node --trace-warnings ...` to show where the warning was created)
> 
>  ERROR  [worker] Worker terminated due to reaching memory limit: JS heap out of memory
> 
>   at new NodeError (node:internal/errors:371:5)
>   at Worker.[kOnExit] (node:internal/worker:276:26)
>   at Worker.<computed>.onexit (node:internal/worker:198:20)
> ```

Now fixed and upgraded to rc
