### ISSUE TITLE
Hot Reload not working with naive-ui elements

### ISSUE THREAD

**Issue by JorgenSQ** [Baiyuetribe/nuxt3-naive-ui-starter#7]
Great work on getting naive-ui to work with nuxt 3, but hot-reload is not working. 

While using your boilerplate, a page with 

```
<template>
<h1>Naive-UI</h1>
<n-button>Button</n-button>
</template>
```

fails to hot-reload, but any other page without naive-ui elements hot-reloads.

**Comment by JorgenSQ** [comment]
**With naive-ui**
![image](https://user-images.githubusercontent.com/89529095/155564220-1644a1a6-fa66-4aea-8c49-bee665e32cff.png)

**Without naive-ui**
![image](https://user-images.githubusercontent.com/89529095/155564522-1117fac6-225c-4f4a-bbf1-ece3b38a79a2.png)

**Comment by Baiyuetribe** [comment]
Please make sure your configuration is correct. I have used it in an official environment and had no problems.
```nuxt.config.js
import { defineNuxtConfig } from 'nuxt3'
import Components from 'unplugin-vue-components/vite';
import { NaiveUiResolver } from 'unplugin-vue-components/resolvers';
// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
    build: {
        transpile: ['naive-ui', 'vueuc'],   // fix dev error: Cannot find module 'vueuc'
    },
    vite: {
        plugins: [
            Components({
                resolvers: [NaiveUiResolver()], // Automatically register all components in the `components` directory
            }),
        ],
        // @ts-expect-error: Missing ssr key
        ssr: {
            noExternal: ['moment', 'naive-ui'],
        },
    }
})

```
I suggest git clone, then npm install, and try starting it again。If you have modified the `nuxt.config.js` file, please restart the npm command.

**Comment by xboxfly15** [comment]
Hot reloading doesn't work if there's naive-ui elements in a page in the pages directory. Hot reloading only works if you use app.vue

**Comment by everatch** [comment]
我也发生同样的问题，但只发生在自己写的 component 上。

```html
<n-card>
  <atoms-graph-basic /> // from /components/atoms/graph/basic.vue
</n-card>
```

第一次读取没有问题，
当我改变这文件， `<n-card>` 读取正常，而 `<atoms-graph-basic />` 会出错误如下
（貌似这问题只出现在 client 环境下？）

![スクリーンショット 2022-03-11 3 32 45](https://user-images.githubusercontent.com/5194717/157731253-80c801f1-2b21-4426-bdc3-96746e2cbdf5.png)

我也尝试用 `vite` 自动读取我的 `component`，但问题没有解决，仍然出现的同样错误

```ts
vite: {
  plugins: [
    Components({
      dirs: ['components'],
      directoryAsNamespace: true,
      resolvers: [NaiveUiResolver()], // Automatically register all components in the `components` directory
    }),
  ],
},
```

**Comment by Baiyuetribe** [comment]
Maybe you can try restart
有时候是需要重启生效的，未来或许可以解决

**Comment by faisalindrianto** [comment]
hello, i encountered this also when I create page inside "pages" folder, it's only work on app.vue, got the same error as @JorgenSQ

<img width="584" alt="Screen Shot 2022-06-10 at 21 35 14" src="https://user-images.githubusercontent.com/43459369/173088965-52034e94-dd07-45b9-8a55-9bb9e57595e7.png">

![Screen Shot 2022-06-10 at 21 36 18](https://user-images.githubusercontent.com/43459369/173089121-5784ff67-151e-4369-bf68-75bc61380000.png)
