### ISSUE TITLE
Warning：重复渲染和重复调用数据api真的很不理解

### ISSUE THREAD

**Issue by Baiyuetribe** [Baiyuetribe/nuxt3-naive-ui-starter#9]
Nuxt3 currently gives the useFetch and useAsyncData data acquisition method is triggered twice, which directly blocked the door to separate front and back-end development. Since the server has already got the data, why does the client have to get it again and again?

Nuxt3目前给出的useFetch和useAsyncData数据获取方式都是触发两次的，这下直接堵上了前后端分离开发的大门。既然服务端已经拿到了数据，为何客户端还要再重复获取一遍？都beta版了，这么重要的问题都没处理好，泪奔啊
https://github.com/nuxt/nuxt.js/issues/13369

**Comment by Baiyuetribe** [comment]
触发原因很奇葩，根据nuxt官方回复是缺少favicon导致浏览器二次请求的。新增图标文件后恢复正常。本项目已初始化一个favicon

**Comment by Baiyuetribe** [comment]
Nuxt3修复favicon导致的问题后，发现使用layouts路由系统后，仍然会有客户端二次请求，所以就算服务端已经渲染好了一切，结果浏览器再次请求一遍数据重新渲染~ 再次泪崩
https://github.com/nuxt/nuxt.js/issues/13369
复现步骤：https://stackblitz.com/edit/github-5qtamp-u2ftnu?file=pages/index.vue

**Comment by Baiyuetribe** [comment]
经验：外链请求API经过server/api中转后，恢复正常。后端如果用其他语言开发，建议二次中转一下

**Comment by ChuanfengLai** [comment]
也遇到这个问题，我使用的解决方案是使用 `useAsyncData` 指定数据的 key，然后判断是 `server` 端，发请求。
`client` 端则直接从 `window.__NUXT__.data` 中获取。
```js
const data = process.server 
? (await useAsyncData('customeKey', () => $fetch(url))).data.value 
: window.__NUXT__.data.customeKey
```

**Comment by Baiyuetribe** [comment]
@codelegant 思路不错，我实际案例用watch解决了
